development:
  adapter: mysql2
  database: snort_event_logger
  username: rails_user
  password: [password]
  host: localhost

test:
  adapter: mysql2
  database: snort_event_logger
  username: rails_user
  password: [password]
  host: localhost

production:
  adapter: mysql2
  database: snort_event_logger
  username: rails_user
  password: [password]
  host: localhost
